"""add address

Revision ID: fde782dddf75
Revises: 20822d744be2
Create Date: 2023-04-02 12:32:20.100453

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde782dddf75'
down_revision = '20822d744be2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    address_table = op.create_table('address',
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.bulk_insert(
        table=address_table,
        rows=[
            {
                "country": "Viet Nam",
                "city": "Da Nang",
                "district": "Son Tra",
                "street": "Ngo Quyen",
                "number": "658",
                "user_id": 1,
                "created_at": datetime.utcnow()
            },
            {
                "country": "Viet Nam",
                "city": "Da Nang",
                "district": "Cam Le",
                "street": "Hoa Nam 3",
                "number": "6",
                "user_id": 1,
                "created_at": datetime.utcnow()
            },
            {
                "country": "Viet Nam",
                "city": "Da Nang",
                "district": "Thanh Khe",
                "street": "Dien Bien Phu",
                "number": "02",
                "user_id": 2,
                "created_at": datetime.utcnow()
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
