"""add role

Revision ID: f915f9abcbd2
Revises: 
Create Date: 2023-04-02 12:16:18.118751

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f915f9abcbd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role_table = op.create_table('role',
        sa.Column('name', sa.Enum('ADMIN', 'STORE_OWNER', 'CUSTOMER', name='roleenum'), server_default='CUSTOMER', nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(
        table=role_table,
        rows=[
            {"name": "ADMIN", "created_at": datetime.utcnow()},
            {"name": "STORE_OWNER", "created_at": datetime.utcnow()},
            {"name": "CUSTOMER", "created_at": datetime.utcnow()},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    # ### end Alembic commands ###
