"""add user

Revision ID: 20822d744be2
Revises: f915f9abcbd2
Create Date: 2023-04-02 12:25:51.765223

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20822d744be2'
down_revision = 'f915f9abcbd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table('user',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('username')
    )
    op.bulk_insert(
        table=user_table,
        rows=[
            {
                "username": "admin",
                "email": "admin@gmail.com",
                "full_name": "Admin Full Name",
                "password": "admin",
                "role_id": 1,
                "created_at": datetime.utcnow()
            },
            {
                "username": "store",
                "email": "store@gmail.com",
                "full_name": "Store Full Name",
                "password": "store",
                "role_id": 2,
                "created_at": datetime.utcnow()
            },
            {
                "username": "customer",
                "email": "customer@gmail.com",
                "full_name": "Customer Full Name",
                "password": "customer",
                "role_id": 3,
                "created_at": datetime.utcnow()
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
